FROM nginx:latest

# Just use root for this
USER root

RUN mkdir /etc/nginx/sites-available
RUN mkdir /etc/nginx/sites-enabled
RUN mkdir /usr/share/nginx/html/landing
RUN mkdir /etc/nginx/config
RUN mkdir -p /etc/letsencrypt/live/localhost

# Copy a simple landing page in for the gateway
COPY ./html /usr/share/nginx/html/landing

# Copy favicons to each site
COPY html/favicon.ico /usr/share/nginx/html/landing/favicon.ico
COPY html/favicon.ico /usr/share/nginx/html/admin/favicon.ico
COPY html/favicon.ico /usr/share/nginx/html/content/favicon.ico

# Copy the http config over
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the config module bits over
COPY ./config /etc/nginx/config

# Copy the server configs over
COPY ./sites-available /etc/nginx/sites-available
RUN ln -s /etc/nginx/sites-available/* /etc/nginx/sites-enabled

RUN ls /etc/letsencrypt/live/localhost

EXPOSE 443