version: "3.0"
services:
    gateway:
        build:
            context: ./development
            dockerfile: dockerfile
        volumes:
            - "./keys/development/cert.crt:/etc/letsencrypt/live/localhost/cert.crt"
            - "./keys/development/key.key:/etc/letsencrypt/live/localhost/key.key"
            # The blog content itself goes in .../dist
            - "../dist:/usr/share/nginx/html/dist"
            # Static assets like PNGs go in .../dist/static
            - "../blogBuilder/app/src/media:/usr/share/nginx/html/dist/static"
