version: "3.0"
services:
    gateway:
        build:
            context: ./development
            dockerfile: dockerfile
        volumes:
            - "./keys/development/cert.pem:/etc/letsencrypt/live/localhost/cert.pem"
            - "./keys/development/key.pem:/etc/letsencrypt/live/localhost/key.pem"
            - "../dist:/usr/share/nginx/html/dist"
            - "../managementUI/frontend/build:/usr/share/nginx/html/admin"
