version: "3.0"
services:
    gateway:
        build:
            context: ./development
            dockerfile: dockerfile
        container_name: gateway
        ports:
            - "80:80"
            - "443:443"

networks:
    default:
        external:
            name: gateway_network
