version: "3.0"
services:
    gateway:
        build:
            context: ./development
            dockerfile: dockerfile
        container_name: gateway
        ports:
            - "80:80"
            - "443:443"
        # volumes:
        #     - "./keys:/etc/letsencrypt/live"
        # - "/etc/letsencrypt/live/rolandw.dev-0001/fullchain.pem:/etc/letsencrypt/live/rolandw.dev-0001/fullchain.pem"
        # - "/etc/letsencrypt/live/rolandw.dev-0001/privkey.pem:/etc/letsencrypt/live/rolandw.dev-0001/privkey.pem"
        # - "/etc/letsencrypt/live:/etc/letsencrypt/live"

networks:
    default:
        external:
            name: gateway_network
