version: "3.0"
services:
    gateway:
        build:
            context: ./production
            dockerfile: dockerfile
        volumes:
            - "/etc/letsencrypt/live/rolandw.dev-0001/fullchain.pem:/etc/letsencrypt/live/rolandw.dev-0001/fullchain.pem"
            - "/etc/letsencrypt/live/rolandw.dev-0001/privkey.pem:/etc/letsencrypt/live/rolandw.dev-0001/privkey.pem"
            # The blog content itself goes in .../dist
            - "../dist:/usr/share/nginx/html/dist"
            # Static assets like PNGs go in .../dist/static
            - "../blogBuilder/app/src/media:/usr/share/nginx/html/dist/static"
            # Mount static admin portal code in .../html/admin
            - "../managementUI/frontend/build:/usr/share/nginx/html/admin"
